export const mockBeerTypes = [
  {
    id: 1,
    korName: '에일',
    engName: 'ALE',
    content: '쓴 맛이 적고 단 맛이 나며, 풀 바디감이 느껴지는 목 넘김이 깔끔한 맥주',
    imageUrl: 'https://beerair-service.s3.ap-northeast-2.amazonaws.com/BEER/TYPE/ale.png',
  },
  {
    id: 2,
    korName: '페일 에일',
    engName: 'PALE_ALE',
    content: '붉은 빛과 맑고 밝은 빛을 띄며, 꽃향기와 같은 풍부한 향이 느껴지는 맥주',
    imageUrl: 'https://beerair-service.s3.ap-northeast-2.amazonaws.com/BEER/TYPE/pale_ale.png',
  },
  {
    id: 3,
    korName: 'IPA',
    engName: 'IPA',
    content: '탄산이 비교적 약하고 강렬한 홉향과 강하고 텁텁한 쓴 맛이 나는 맥주',
    imageUrl: 'https://beerair-service.s3.ap-northeast-2.amazonaws.com/BEER/TYPE/ipa.png',
  },
  {
    id: 4,
    korName: '라거',
    engName: 'LAGER',
    content: '황금빛의 풍부한 탄산과 청량감을 가진 맥주',
    imageUrl: 'https://beerair-service.s3.ap-northeast-2.amazonaws.com/BEER/TYPE/lager.png',
  },
  {
    id: 5,
    korName: '필스너',
    engName: 'PILSNER',
    content: '밝고 투명한 노란빛으로, 단 맛과 쓴 맛이 어우러진 깔끔한 맛의 맥주',
    imageUrl: 'https://beerair-service.s3.ap-northeast-2.amazonaws.com/BEER/TYPE/pilsner.png',
  },
  {
    id: 6,
    korName: '밀맥주',
    engName: 'WHEAT_BEER',
    content: '밀 맥아의 비율이 50% 이상으로, 뿌옇고 엷은 빛깔의 부드러운 밀맥주',
    imageUrl: 'https://beerair-service.s3.ap-northeast-2.amazonaws.com/BEER/TYPE/wheat_beer.png',
  },
  {
    id: 7,
    korName: '스타우트',
    engName: 'STOUT',
    content: '포터보다 더 짙은 검은색을 띄며, 탄 맛과 쓴 맛도 더 강한 흑맥주',
    imageUrl: 'https://beerair-service.s3.ap-northeast-2.amazonaws.com/BEER/TYPE/stout.png',
  },
  {
    id: 8,
    korName: '포터',
    engName: 'PORTER',
    content: '도수가 높고 비교적 달콤한 맛이 나며, 짙고 그윽한 향이 나는 흑맥주',
    imageUrl: 'https://beerair-service.s3.ap-northeast-2.amazonaws.com/BEER/TYPE/porter.png',
  },
  {
    id: 9,
    korName: '라들러',
    engName: 'RADLER',
    content: '도수가 낮고 라거 맥주를 베이스로 음료수를 블렌딩해 탄산과 단 맛이 강한 맥주',
    imageUrl: 'https://beerair-service.s3.ap-northeast-2.amazonaws.com/BEER/TYPE/radler.png',
  },
  {
    id: 10,
    korName: '발포주',
    engName: 'LOW_MALT_BEER',
    content: '맥아 함량이 매우 적은 유사 맥주로, 먹기 편한 가벼운 맛의 맥주',
    imageUrl: 'https://beerair-service.s3.ap-northeast-2.amazonaws.com/BEER/TYPE/low_malt_beer.png',
  },
];
